name: 'proton-delete-schedule'
on:
  schedule:
    - cron: '0/1 * * * *'

jobs:
  delete:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - name: echo test
        run: |
          echo "test"
